steps:
  - name: node
    entrypoint: npm
    args: ['install']
  - name: node
    entrypoint: npm
    args: ['test']
  - name: node
    # entrypoint: npm
    # args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull gcr.io/$PROJECT_ID/github.com/neilghosh/simple-node-service:latest || exit 0']
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/github.com/neilghosh/simple-node-service:$_BUILD_NUM',
                '--cache-from', 'gcr.io/$PROJECT_ID/github.com/neilghosh/simple-node-service:latest',
    '.' ]
substitutions:
    _BUILD_NUM: $SHORT_SHA    
images:
  - 'gcr.io/$PROJECT_ID/github.com/neilghosh/simple-node-service:$_BUILD_NUM'
