apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
 name: simple-node-app
description: main application pipeline
serialPipeline:
 stages:
 - targetId: qsdev
   profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
 name: qsdev
description: development cluster
gke:
 cluster: projects/demoneil/locations/us-central1/clusters/demo-cluster