apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app
spec:
  selector:
    matchLabels:
      run: simple-node-app
  replicas: 1
  template:
    metadata:
      labels:
        run: simple-node-app
    spec:
      containers:
      - name: simple-node-app
        image: my-app-image
        ports:
        - containerPort: 8080    

